apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: demo2
  labels:
    app: nginx
    status: testando
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.20
          ports:
            - containerPort: 80
