apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namePrefix: dev-

commonLabels:
  env: demo3
  owner: danielgomes

images:
  - name: nginx:1.21
    newName: nginx
    newTag: '1.15'

configMapGenerator:
  - name: app-properties
    literals:
      - APP_WELCOME=App v1
